name: C/C++ CMake CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
    BUILD_TYPE: Release

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: configure CMake
      run: module load hdf5/1.14.4 cgns/4.4.0 && cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja
    - name: Ninja Build
      working-directory: ${{github.workspace}}/build
      run: ninja